### ISSUE TITLE
invalid application credentials

### ISSUE THREAD

**Issue by yqchilde** [guzhongren/algolia-docsearch-upload-action#16]
出现报错如下：
<img width="1116" alt="image" src="https://github.com/guzhongren/algolia-docsearch-upload-action/assets/36953759/61b44511-5c8e-4f02-bf37-44854e70ea60">

我的配置如下：
```yml
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push indices to Algolia
        uses: guzhongren/algolia-docsearch-upload-action@v2.0.0
        env:
            APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
            ADMIN_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
            FILE_PATH: './crawlerConfig.json'
            INDEX_NAME: "search"
```
